---
title: "Homework10.5"
author: "Alyssa Walch"
date: "October 5, 2016"
output: pdf_document
---
#1 Article 1: Data Processing with dplyr & tidyr  
%>% This operator is great when you a lot if data to organize. It helps simplify nested if function making the code look clean. 
Tidyr has four main functions: gather, spread, separate, and unite. The gather function takes multiple columns and reorganizes it. The variables are gathered into a single variable. The spread function separates a variable into two variables. This is used when a column has more variables than are important. The unite function puts two variables together.  Lastly, the spread function is used to reformat data. It moves it from a long string into a wider format. The information gets moved across multiple columns.     
Dyplr functions consist of select, filter, group_by, summarise, arrange, join, and mutate.  Select allows you to pick desired variables to view. This can be beneficial if you are only looking for certain items and can save space. Filter allows you to give specific condition to bring up certain data. You can pull all the relevant data and leave out the rest. Group_by is similar but allows you to pull up different categories.  You can pull up different categories that have similar needs. The summarise function gives a summary of statistical analysis. For instance, you can summarize the means. The arrange function allows you to order variables in various orders.  This can let you put them in ascending order or descending order, etc. The join function puts two datasets into one. When there are commonalities in datasets it is nice to merge them. Lastly is the mutate function creates new functions from old ones. This allows you to maintain the old variable while creating new ones.    

#2 Article 2: Tidy Data  
This article is all about organizing data. There are three rules to tidy data: first is each variable must have its own column, second is each observation must have its own row, and thirdly is each value must have its own cell.  All three of these rules go together and must all be completed.  This leads to two more rules, one is that each dataset must be in a tibble and second is each variable must be in a column. These rules lead to tidy data.  Tidy data is important because it leads to consistent data structure. Uniformity is great because it makes the data easier to work with. Next, variables placed in columns are easier for R to read.  R works with vectors making this extremely necessary.   
	There are two main reasons that data is not tidy. The first is that people are not aware of what goes into tidy data. The best way to learn is to spend a lot of time working with the data. The second reason is that data is arranged in an order other than analysis.  Sometimes, it is best to put in the work in the beginning to have organized data instead of focusing on what is easiest to input. To have organized data it is crucial to identify the variables and observations. Two common problems that arise are one variable may spread across multiple columns and the other is that one observation might be scattered across multiple rows.  These two problems can be fixed by either the gather or spread function.   
	The gather function can be used to find the necessary columns. You should set columns that represent values not variables. When observations are spread across multiple rows the spread function can be used to collect the needed information.  The unite function can be used if a single variable is spread across multiple columns. The separate function pulls apart one column into multiple columns.  If a table has two variables that need to be split, the separate function is the best to use.  Separate function leaves the column type in its original form, if it was characters for instance, it will stay that way.  Unite is the opposite of separate. Unite puts multiple columns into one.   
	Often times there missing variables. There are two ways they can be missing, explicitly, when it is flagged, or implicitly, when it is just not present. Explicit values can be turned into implicit values by na.rm = TRUE in gather().  Missing values can be imputed by the fill function. This can help reduce the number of missing values. Complete is another function that is important to tidy data.  It takes a set of columns, and finds all the unique combinations.  

#3 Article 3: Going deeper with dplyr: New features in 0.3 and 0.4   
This article goes through the NYC data set. It uses select to pull up all the data by month and data.  Then, rename the tail column to tailnum by %>% rename (tail = tailnum).  Columns can be chosen by filter, between, slice, sample_n, top_n, or distinct.  Filter is used to pick all fights that leave between 6:00 and 6:05.  It is done by filter( dep_time >=600, dep_time <= 605).  In a similar way, the data can be grouped.  Slice allows you fliter data by the position by row.To create new variables, you can use mutate, transmute, and add_rownames. Mutate can be used to create a new variable. Flights %>% mutate(speed = distance/air_time*60) gives a new variable called speed from the distance and air_time variables. Transmute is similar to mutate but only keeps the new variable. Grouping and counting can be done by sumamrise, tally, ount, group, n_group, and ungroup.  These all allow you to collect different types of data. For instance, flights %>% group_by(month)  %>% tally() gives you only the data grouped by month.Data frames can be created through the data_frame function.  This is good because it never munges column names or coerces column types. It also doesn’t add row names.  There are a few different join functions.  These pull together information for various reasons.   

#4 Article 4: dplyr with NYC Flights  
dyplr is a tool for exploration and transformation.It is used because it is easy to read and to use. The data is printed in an easy to read formation. It is nice because it is simple, it makes it hard to accidently display data that you do not want to see. There are five functions: filter, select, arrange, mutate, and summarize. Filter is used for sub-setting variables. Select is used for sub-setting rows. Arrange is used for re-ordering rows. Mutate is for adding new columns. And lastly, summarize is for reducing each group into a smaller number of statistics. Chaining is used to make the data easier to read. It is used to replace nesting. The windows function returns n values.  Mean, for example, returns one value.  

There are four binary verbs:  
###1.1 Inner_join → matching x and y  
###1.2 left_join →all x and matching y  
###1.3 semi_join → all x with matching in y  
###1.4 anti_join → all x without matching in y  

